services:
  - type: web
    name: browser-automation-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
    autoDeploy: true
